from pathlib import Path

from app.adapters.base import BaseModelAdapter
from app.services.storage_service import MOCK_PNG_BYTES
from app.utils.files import ensure_dir
from app.utils.ids import new_id


class MockAdapter(BaseModelAdapter):
    output_kind = "json"

    def build_payload(self, inputs: dict, params: dict) -> dict:
        self.validate_inputs(inputs, params)
        return {
            "model": self.model_id,
            "inputs": inputs,
            "parameters": params,
        }

    def submit(self, payload: dict) -> dict:
        return {
            "provider_task_id": new_id("mock_task"),
            "status": "submitted",
            "payload_echo": payload,
        }

    def poll(self, task_id: str) -> dict:
        return {
            "provider_task_id": task_id,
            "status": "success",
            "output_kind": self.output_kind,
            "artifacts": [],
        }

    def download_outputs(self, response: dict, output_dir: str) -> list:
        output_path = ensure_dir(output_dir)
        kind = response.get("output_kind") or self.output_kind
        expected = response.get("expected_output_path")
        if kind == "image":
            target = Path(expected) if expected else output_path / "first_frame.png"
            target.write_bytes(MOCK_PNG_BYTES)
        elif kind == "video":
            target = Path(expected) if expected else output_path / "video.mp4"
            target.write_bytes(b"Mock video bytes generated by MockAdapter.\n")
        else:
            target = Path(expected) if expected else output_path / "response.json"
            target.write_text("{}", encoding="utf-8")
        return [str(target)]

    def parse_artifacts(self, response: dict) -> list:
        return response.get("artifacts") or []


class MockVideoAdapter(MockAdapter):
    output_kind = "video"


class MockImageAdapter(MockAdapter):
    output_kind = "image"


class MockChatAdapter(MockAdapter):
    output_kind = "json"

    def submit(self, payload: dict) -> dict:
        response = super().submit(payload)
        response["json"] = self._mock_json(payload)
        response["content"] = self._mock_content(payload, response["json"])
        response["message"] = {
            "content": response["content"],
            "inputs": payload.get("inputs", {}),
        }
        return response

    def download_outputs(self, response: dict, output_dir: str) -> list:
        target_dir = ensure_dir(output_dir)
        target = Path(target_dir) / "chat_response.json"
        target.write_text(str(response), encoding="utf-8")
        return [str(target)]

    @staticmethod
    def _mock_json(payload: dict) -> dict:
        inputs = payload.get("inputs") or {}
        schema = inputs.get("response_schema") or {}
        required = schema.get("required") or []
        if "t2v" in required:
            return {
                "t2v": (
                    "Cinematic vertical short video prompt. Keep the main subject clear, "
                    "lighting soft, movement natural, and camera motion stable."
                )
            }
        if "first_frame_image" in required or "i2v" in required:
            t2v_text = inputs.get("t2v_prompt") or inputs.get("user_prompt") or ""
            return {
                "first_frame_image": (
                    "High quality first-frame image prompt with the subject centered, "
                    "consistent wardrobe, pose, lighting, and scene mood."
                ),
                "i2v": (
                    f"{str(t2v_text).strip() or 'Generate a natural video from the first frame.'}\n"
                    "Use the first frame as the starting image, preserve identity and composition, "
                    "and animate with smooth motion."
                ),
            }
        if "r2v_flash" in required:
            t2v_text = inputs.get("t2v_prompt") or inputs.get("user_prompt") or ""
            return {
                "r2v_flash": (
                    f"{str(t2v_text).strip() or 'Generate dynamic video from references.'}\n"
                    "Preserve reference identity, facial details, wardrobe, pose, and visual style."
                )
            }
        if "full_i2i_prompt" in required:
            t2i_text = inputs.get("t2i") or inputs.get("t2i_prompt") or inputs.get("first_frame_image") or ""
            return {
                "full_i2i_prompt": (
                    f"{str(t2i_text).strip() or 'Use the input portrait as visual reference.'}\n"
                    "Preserve identity, body shape, wardrobe, facial details, lighting, and camera composition. "
                    "Convert the text-to-image prompt into an image-to-image prompt suitable for batch testing."
                )
            }
        return {}

    @staticmethod
    def _mock_content(payload: dict, data: dict) -> str:
        inputs = payload.get("inputs") or {}
        if inputs.get("task") == "reverse_video_prompts" and not inputs.get("response_schema"):
            return (
                "## 画质与风格\n"
                "画面质感：高清、细节清晰、电影级光影。\n"
                "整体风格：写实短视频风格，画面干净稳定。\n\n"
                "## 人物与造型\n"
                "成年人物设定：成年年轻人物，气质自然。\n"
                "五官：面部特征清晰，表情稳定。\n"
                "发型：发丝自然，随动作轻微联动。\n"
                "体态：站姿自然，动作流畅。\n"
                "服装：服装材质清晰，颜色与场景协调。\n\n"
                "## 场景与光影\n"
                "场景：单场景空间，主体突出。\n"
                "背景元素：背景简洁，环境元素服务主体。\n"
                "光线方向：柔和自然光包裹主体。\n"
                "色彩氛围：自然色调，整体观感统一。\n\n"
                "## 运镜&动作规则\n"
                "镜头类型：单镜头，一镜到底。\n"
                "机位/构图：中景构图，主体居中。\n"
                "动作节奏：人物完成自然连贯动作，身体、手部、表情、发丝和服装产生真实联动。\n\n"
                "## 声音与对白\n"
                "环境音：轻微环境声。\n"
                "BGM：轻柔氛围音乐。\n"
                "对白：无对白\n"
            )
        if data:
            return str(data)
        return "Mock chat response"
